### REGISTER 
POST http://localhost:3000/auth/register 
content-type: application/json

{
    "email" : "wuetoix3333@gmail.com",
    "password" : "123456789aA@@"
}
### LOGIN 
POST http://localhost:3000/auth/login 
content-type: application/json

{
    "email" : "wuetoix3333@gmail.com",
    "password" : "123456789aA@@@"
}
### FORGOT PASSWORD 
POST http://localhost:3000/auth/forgotPwd
content-type: application/json

{
    "email" : "wuetoix3333@gmail.com"
}
### RESET PASSWORD 
GET http://localhost:3000/auth/resetPwd?secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ind1ZXRvaXgzMzMzQGdtYWlsLmNvbSIsImlhdCI6MTY2MjUzNzQzNywiZXhwIjoxNjYyNTQ4MjM3fQ.WvXBvJT_vNa2wjeBZ4SCOi_44ATvjlN18NXK0Ki7aV8

### UPDATE PASSWORD
PATCH  http://localhost:3000/auth/updatePwd
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ind1ZXRvaXgzMzMzQGdtYWlsLmNvbSIsImlhdCI6MTY2MjUzNzQzNywiZXhwIjoxNjYyNTQ4MjM3fQ.WvXBvJT_vNa2wjeBZ4SCOi_44ATvjlN18NXK0Ki7aV8

{
    "password" : "123456789aA@@@" 
}