GET http://localhost:8000/api/v1/

@ENDPOINT=http://localhost:8000/api/v1
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMTcwN2M3NzY4NDMyYTRhM2JkNWRjZSIsInVzZXJuYW1lIjoibmd1eWVubGluZyIsImFjdGlvbiI6ImZvcmdvdCIsImlhdCI6MTY2MjUyMjcyNiwiZXhwIjoxNjYyNzgxOTI2fQ.Vp_XGgd1L_cFTyEeyXFIoh7y0th5R7xh6IkBBtjDhfk
### register
POST {{ENDPOINT}}/add/user
Content-Type: application/json

{
    "email": "nguyenling@gmail.com",
    "username": "nguyenling",
    "password": "root",
    "re_password": "root"
}
###
POST {{ENDPOINT}}/login
Content-Type: application/json

{
    "email": "nguyenling@gmail.com",
    "password": "12345678"
}



###
#change password

PUT {{ENDPOINT}}/change
Content-Type:  application/json
Authorization:  Bearer {{TOKEN}}

{
    "password": "12345678",
    "re_password": "12345678"
}
###
#forgot password
POST {{ENDPOINT}}/forgot
Content-Type:  application/json

{
    "email": "nguyenling@gmail.com"
}
