GET http://localhost:8000/api/v1/

@ENDPOINT=http://localhost:8000/api/v1
### register
POST {{ENDPOINT}}/add/user
Content-Type: application/json

{
    "email": "nguyenling@gmail.com",
    "username": "nguyenling",
    "password": "root",
    "re_password": "root"
}
###
POST {{ENDPOINT}}/login
Content-Type: application/json

{
    "email": "nguyenling@gmail.com",
    "password": "root"
}

###
#forgot password
POST {{ENDPOINT}}/forgot
Content-Type:  application/json

{
    "email": "nguyenling@gmail.com"
}
