export enum NotificationType {
  BOOK_RENT = 'BOOK_RENT',
  RENT_ACCEPTED = 'RENT_ACCEPTED',
  RENT_REJECTED = 'RENT_REJECTED',
  BOOK_ADDED = 'BOOK_ADDED',
  CSV_EXPORT_SUCCESSFUL = 'CSV_EXPORT_SUCCESSFUL'
}